# Generated by Django 5.1.4 on 2026-05-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bank nomi')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logotip URL')),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimal foiz stavkasi (%)')),
                ('max_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maksimal foiz stavkasi (%)')),
                ('min_term_months', models.PositiveIntegerField(default=3, verbose_name='Minimal muddat (oy)')),
                ('max_term_months', models.PositiveIntegerField(default=360, verbose_name='Maksimal muddat (oy)')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=15, verbose_name="Minimal kredit summasi (so'm)")),
                ('max_amount', models.DecimalField(decimal_places=2, default=5000000000, max_digits=15, verbose_name="Maksimal kredit summasi (so'm)")),
                ('credit_type', models.CharField(choices=[('consumer', "Iste'mol krediti"), ('mortgage', 'Ipoteka'), ('auto', 'Avtokredit'), ('business', 'Biznes kredit')], default='consumer', max_length=20, verbose_name='Kredit turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banklar',
                'ordering': ['min_rate'],
            },
        ),
    ]
